import moment from 'moment-timezone';
import { INTERVIEW_TYPES } from '../constants.js';
import { SESSION_TYPES } from '../lib/session-labels.js';
import { mockCallBridge } from './mock-call-bridge.service.js';

const chatStates = new Map();
const DEFAULT_TZ = 'Asia/Kolkata';

const BASIC_FIELDS = [
  'job_profile',
  'job_description',
  'experience_required',
  'question_count',
  'candidate_name',
  'candidate_email',
];

function chatKey(clientId, userId) {
  return `${userId || 'anon'}:${clientId || 'default'}`;
}

function emptyState() {
  return {
    step: 'await_basics',
    data: {
      timezone: DEFAULT_TZ,
      schedule_mode: null,
      scheduled_at: null,
      question_source: null,
      questions: [],
      ai_question_pool: [],
      history_questions: [],
      from_history_template: false,
    },
  };
}

function questionSourceOptions(data) {
  const options = [];
  const showHistory =
    data.from_history_template === true &&
    Array.isArray(data.history_questions) &&
    data.history_questions.length > 0;

  if (showHistory) {
    options.push({ value: 'history', label: 'Use questions from history' });
  }
  options.push(
    { value: 'ai', label: 'Generated by UI (AI)' },
    { value: 'manual', label: 'Your list' }
  );

  const seen = new Set();
  return options.filter((opt) => {
    if (seen.has(opt.value)) return false;
    seen.add(opt.value);
    return true;
  });
}

/** Browser video is the only supported interview mode — skip type selection. */
function advanceToQuestionSource(state, reply = '✅ All required fields received. Setting up browser video interview.') {
  state.data.interview_type = INTERVIEW_TYPES.BROWSER_VIDEO;
  state.step = 'choose_question_source';
  return {
    reply,
    step: state.step,
    summary: { ...state.data },
    ui: {
      type: 'select',
      field: 'question_source',
      label: 'How do you want to provide interview questions?',
      options: questionSourceOptions(state.data),
    },
    done: false,
  };
}

function normalizePhone(raw) {
  const s = String(raw || '').replace(/[\s\-()]/g, '');
  if (!s) return null;
  if (/^\+91\d{10}$/.test(s)) return s;
  if (/^91\d{10}$/.test(s)) return `+${s}`;
  if (/^\d{10}$/.test(s)) return `+91${s}`;
  if (/^\+?\d{10,15}$/.test(s)) return s.startsWith('+') ? s : `+${s}`;
  return null;
}

function parsePhonesList(text) {
  return String(text || '')
    .split(/[,;\n]+/)
    .map((p) => normalizePhone(p.trim()))
    .filter(Boolean);
}

function parseListField(text) {
  return String(text || '')
    .split(/[,;\n]+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function parseEmailsList(text) {
  return parseListField(text).map((e) => e.toLowerCase());
}

function buildCandidates(data) {
  const phones = data.candidate_phones?.length
    ? data.candidate_phones
    : data.candidate_phone
      ? [data.candidate_phone]
      : [];
  const names = data.candidate_names?.length
    ? data.candidate_names
    : parseListField(data.candidate_name);
  const emails = data.candidate_emails?.length
    ? data.candidate_emails
    : parseEmailsList(data.candidate_email);

  return phones.map((phone, i) => ({
    name: names[i] || names[0] || `Candidate ${i + 1}`,
    email: emails[i] || emails[0] || '',
    phone,
  }));
}

function validateCandidateAlignment(data, phones) {
  const errors = [];
  const names = data.candidate_names?.length
    ? data.candidate_names
    : parseListField(data.candidate_name);
  const emails = data.candidate_emails?.length
    ? data.candidate_emails
    : parseEmailsList(data.candidate_email);

  if (phones.length > 1) {
    if (names.length > 1 && names.length !== phones.length) {
      errors.push(
        `You entered ${phones.length} phone numbers but ${names.length} names. Use one name for all, or one per phone.`
      );
    }
    if (emails.length > 1 && emails.length !== phones.length) {
      errors.push(
        `You entered ${phones.length} phone numbers but ${emails.length} emails. Use one email for all, or one per phone.`
      );
    }
    if (emails.length > 1) {
      emails.forEach((e, i) => {
        if (!isValidEmail(e)) errors.push(`Invalid email at position ${i + 1}: ${e}`);
      });
    }
  }
  return errors;
}

function parseTimeEntriesFromMessage(message) {
  const timeEntries = [];
  const lines = String(message || '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
  for (const line of lines) {
    const match = line.match(/^(\+?\d{10,15})\s*:\s*(.+)$/i);
    if (!match) continue;
    const phone = normalizePhone(match[1].trim());
    if (phone) {
      timeEntries.push({ phoneNumber: phone, dateTimeStr: match[2].trim() });
    }
  }
  return timeEntries;
}

function parseDatetimeInput(raw, tz = DEFAULT_TZ) {
  const text = String(raw || '').trim();
  if (!text) return { ok: false };

  const m = moment.tz(
    text,
    [
      'YYYY-MM-DD HH:mm',
      'DD-MM-YYYY HH:mm',
      'YYYY-MM-DDTHH:mm',
      'DD-MM-YYYY hh:mm A',
      'DD-MM-YYYY h:mm A',
    ],
    tz
  );
  if (!m.isValid()) return { ok: false };
  if (m.isBefore(moment().tz(tz))) {
    return { ok: false, error: 'Scheduled time must be in the future' };
  }
  return {
    ok: true,
    scheduled_at: m.format('YYYY-MM-DD HH:mm:ss'),
    scheduled_at_utc: m.clone().utc().format('YYYY-MM-DD HH:mm:ss'),
  };
}

const SCHEDULE_DATETIME_FORMAT_HINT = 'DD-MM-YYYY 02:30 PM';
const SCHEDULE_DATETIME_EXAMPLE = '15-06-2026 02:30 PM';

function laterDatetimePrompt(candidates) {
  if (candidates.length <= 1) {
    return {
      reply: `Enter scheduled date & time (Asia/Kolkata). Format: ${SCHEDULE_DATETIME_FORMAT_HINT}`,
      ui: {
        type: 'datetime',
        field: 'scheduled_at',
        label: 'Scheduled date & time',
        placeholder: SCHEDULE_DATETIME_EXAMPLE,
      },
    };
  }
  const examples = candidates
    .slice(0, 3)
    .map((c) => `${c.phone} : 15-12-2026 11:00 AM`)
    .join('\n');
  return {
    reply:
      `📅 You have ${candidates.length} candidates.\n\n` +
      `Same time for all: enter one date/time (e.g. ${SCHEDULE_DATETIME_EXAMPLE})\n\n` +
      `Different times: one line per number:\n` +
      `${examples}${candidates.length > 3 ? '\n...' : ''}`,
    ui: {
      type: 'datetime',
      field: 'scheduled_at',
      label: 'Schedule (one time or per-number lines)',
      placeholder: SCHEDULE_DATETIME_EXAMPLE,
      multiline: true,
      candidate_count: candidates.length,
    },
  };
}

function isValidEmail(email) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email || '').trim());
}

/** Parse initial job/candidate block only (ignore interview type & phone here). */
export function parseBasicsPrompt(text) {
  const out = {};
  const lines = String(text || '').split(/\r?\n/);
  const keyMap = {
    'job profile': 'job_profile',
    profile: 'job_profile',
    'job description': 'job_description',
    description: 'job_description',
    'experience required': 'experience_required',
    experience: 'experience_required',
    'number of questions to ask': 'question_count',
    'number of questions': 'question_count',
    questions: 'question_count',
    name: 'candidate_name',
    'candidate name': 'candidate_name',
    names: 'candidate_name',
    email: 'candidate_email',
    emails: 'candidate_email',
  };

  for (const line of lines) {
    const m = line.match(/^\s*([^:]+):\s*(.*)\s*$/i);
    if (!m) continue;
    const key = keyMap[m[1].trim().toLowerCase()];
    if (!key) continue;
    let val = m[2].trim();
    if (key === 'question_count') {
      const n = parseInt(val, 10);
      if (Number.isFinite(n)) out[key] = Math.min(15, Math.max(1, n));
    } else if (key === 'candidate_email') {
      if (!val) {
        out.candidate_email = '';
        out.candidate_emails = [];
      } else {
        const list = val.split(/[,;]/).map((e) => e.trim().toLowerCase()).filter(Boolean);
        out.candidate_emails = list;
        out.candidate_email = list.join(', ');
      }
    } else if (key === 'candidate_name') {
      if (!val) {
        out.candidate_name = '';
        out.candidate_names = [];
      } else {
        const list = parseListField(val);
        out.candidate_names = list;
        out.candidate_name = list.join(', ');
      }
    } else {
      out[key] = val;
    }
  }
  return out;
}

function validateBasics(data) {
  const errors = [];
  if (!data.job_profile?.trim()) errors.push('Job Profile is required');
  if (!data.job_description?.trim()) errors.push('Job Description is required');
  if (data.experience_required === undefined || data.experience_required === null || data.experience_required === '') {
    errors.push('Experience Required is required');
  }
  const qc = Number(data.question_count);
  if (!Number.isFinite(qc) || qc < 1 || qc > 15) {
    errors.push('Number of Questions to Ask must be between 1 and 15');
  }
  if (!data.candidate_name?.trim()) errors.push('Name is required');
  const emails = data.candidate_emails?.length
    ? data.candidate_emails
    : parseEmailsList(data.candidate_email);
  if (!emails.length) errors.push('Email is required');
  else {
    emails.forEach((e, i) => {
      if (!isValidEmail(e)) {
        errors.push(emails.length > 1 ? `Invalid email at position ${i + 1}` : 'Email format is invalid');
      }
    });
  }
  return errors;
}

function buildBasicsFormatTemplateReply() {
  return (
    `There are errors in your format. Please use the below format:\n\n` +
    `Job Profile :\n` +
    `Job Description :\n` +
    `Experience :\n` +
    `Number of Questions to Ask :\n` +
    `Name :\n` +
    `Email :`
  );
}

function basicsSummary(data) {
  const candidates = data.candidates?.length ? data.candidates : buildCandidates(data);
  const candidateLines =
    candidates.length <= 1
      ? `• Name: ${data.candidate_name}\n• Email: ${data.candidate_email}`
      : candidates
          .map((c, i) => `• Candidate ${i + 1}: ${c.name} — ${c.email} — ${c.phone}`)
          .join('\n');
  return (
    `Received:\n` +
    `• Job Profile: ${data.job_profile}\n` +
    `• Job Description: ${data.job_description}\n` +
    `• Experience Required: ${data.experience_required}\n` +
    `• Number of Questions: ${data.question_count}\n` +
    candidateLines
  );
}

function shufflePick(arr, n) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, n);
}

function resolveQuestionCount(data) {
  const n = Number(data?.question_count);
  if (Number.isFinite(n) && n >= 1) return Math.min(15, Math.trunc(n));
  return null;
}

function pickHistoryQuestions(data, historyQuestions) {
  const pool = (historyQuestions || []).filter(Boolean);
  const need = resolveQuestionCount(data) ?? pool.length;
  const picked = pool.slice(0, Math.max(1, need));
  return picked.map((q, i) => ({
    question: typeof q === 'string' ? q : q.question || String(q),
    order: i + 1,
  }));
}

async function generateQuestionPool(data, poolSize = 25) {
  const texts = await mockCallBridge.generateMockInterviewQuestions({
    jobTitle: data.job_profile,
    experience: String(data.experience_required || ''),
    description: data.job_description || '',
    count: poolSize,
  });
  return texts.filter(Boolean).map((q, i) => ({
    order: i + 1,
    question: q,
    category: 'general',
    required: true,
    source_type: 'ai_generated',
  }));
}

function parseManualQuestions(text, needCount) {
  const lines = String(text || '')
    .split(/\r?\n/)
    .map((l) => l.replace(/^\s*\d+[\).\]:]\s*/, '').trim())
    .filter(Boolean);
  if (lines.length < needCount) return { ok: false, lines };
  return {
    ok: true,
    questions: lines.slice(0, needCount).map((q, i) => ({
      order: i + 1,
      question: q,
      source_type: 'custom',
    })),
  };
}

function buildSchedulePayload(data) {
  const scheduledAt =
    data.schedule_mode === 'now'
      ? moment().tz(data.timezone || DEFAULT_TZ).format('YYYY-MM-DD HH:mm:ss')
      : data.scheduled_at;

  const interviewQuestions = (data.questions || []).map((q, i) => ({
    order: q.order ?? i + 1,
    question: q.question || q,
    category: q.category || null,
    required: true,
    source_type: q.source_type || 'custom',
  }));

  return {
    candidates: data.candidates?.length ? data.candidates : buildCandidates(data),
    candidate_name: data.candidate_name,
    candidate_email: data.candidate_email,
    candidate_phone: data.candidate_phones?.[0] || data.candidate_phone || null,
    candidate_schedules: data.candidate_schedules || null,
    job_title: data.job_profile,
    interview_type: data.interview_type,
    scheduled_at: scheduledAt,
    schedule_mode: data.schedule_mode || 'now',
    timezone: data.timezone || DEFAULT_TZ,
    send_invite: true,
    question_count: resolveQuestionCount(data) || interviewQuestions.length || 0,
    interview_questions: interviewQuestions.length ? interviewQuestions : undefined,
    question_source: data.question_source || null,
    source: 'schedule_chat',
    session_type: SESSION_TYPES.INTERVIEW,
    job_meta: {
      title: data.job_profile,
      description: data.job_description,
      experience: data.experience_required,
    },
  };
}

function buildConfirmText(data) {
  const typeLabel = data.interview_type === INTERVIEW_TYPES.VOICE_CALL ? 'Telephony' : 'Browser';
  const candidates = data.candidates?.length ? data.candidates : buildCandidates(data);
  const phoneLine =
    candidates.length <= 1
      ? data.candidate_phone
        ? `• Phone: ${data.candidate_phone}\n`
        : ''
      : `• Candidates (${candidates.length}):\n${candidates.map((c) => `  - ${c.name} (${c.phone})`).join('\n')}\n`;
  const whenLine =
    data.schedule_mode === 'now'
      ? 'Now'
      : data.candidate_schedules?.length > 1
        ? data.candidate_schedules
            .map((s) => `  - ${s.name} (${s.phone}): ${s.scheduled_at}`)
            .join('\n')
        : data.scheduled_at;
  return (
    `Review before scheduling:\n` +
    `• ${basicsSummary(data)}\n` +
    `• Interview type: ${typeLabel}\n` +
    phoneLine +
    `• Questions: ${data.questions?.length || 0} (${data.question_source === 'ai' ? 'AI random pick' : data.question_source === 'history' ? 'from history' : 'your list'})\n` +
    `• When: ${whenLine}\n\n` +
    `Click Confirm to schedule.`
  );
}

export const interviewChatScheduleService = {
  reset(clientId, userId) {
    chatStates.delete(chatKey(clientId, userId));
  },

  getState(clientId, userId) {
    const key = chatKey(clientId, userId);
    if (!chatStates.has(key)) chatStates.set(key, emptyState());
    return chatStates.get(key);
  },

  async handleInput({
    clientId,
    userId,
    message = '',
    action = null,
    value = null,
    phones = null,
    questionsText = null,
    historyPrompt = null,
    historyQuestions = null,
    fromHistoryTemplate = null,
  }) {
    const key = chatKey(clientId, userId);
    let state = chatStates.get(key);
    if (!state) {
      state = emptyState();
      chatStates.set(key, state);
    }

    if (action === 'reset') {
      state = emptyState();
      chatStates.set(key, state);
      return {
        reply: 'Session reset. Paste your job and candidate details below.',
        step: 'await_basics',
        ui: { type: 'basics_prompt' },
        done: false,
      };
    }

    if (action === 'resume_from_history') {
      const storedQuestions = Array.isArray(historyQuestions) ? historyQuestions : [];
      const parsed = parseBasicsPrompt(historyPrompt || message || '');
      Object.assign(state.data, parsed);
      state.data.interview_type = INTERVIEW_TYPES.BROWSER_VIDEO;
      state.data.from_history_template = true;
      state.data.history_questions = storedQuestions.filter(Boolean);
      const parsedCount = resolveQuestionCount(state.data);
      if (parsedCount != null && state.data.history_questions.length > parsedCount) {
        state.data.question_count = parsedCount;
      }
      const errors = validateBasics(state.data);
      if (errors.length) {
        return {
          reply: buildBasicsFormatTemplateReply(),
          step: 'await_basics',
          errors,
          ui: { type: 'basics_prompt' },
          done: false,
        };
      }
      return advanceToQuestionSource(state, 'Template loaded. Browser video interview will be used.');
    }

    /* ─── Confirm (must run before await_basics — empty state + confirm used to re-validate) ─── */
    if (action === 'confirm') {
      if (state.step !== 'confirm' || !state.data?.job_profile) {
        return {
          reply: '⚠️ Nothing to confirm. Click Reset and complete the flow again.',
          step: state.step,
          done: false,
        };
      }
      const payload = buildSchedulePayload(state.data);
      return {
        reply: 'Scheduling interview…',
        schedulePayload: payload,
        done: true,
      };
    }

    /* ─── Step 1: basics paste ─── */
    if (state.step === 'await_basics' || action === 'submit_basics') {
      const parsed = parseBasicsPrompt(message);
      Object.assign(state.data, parsed);
      if (fromHistoryTemplate === true && Array.isArray(historyQuestions) && historyQuestions.length) {
        state.data.from_history_template = true;
        state.data.history_questions = historyQuestions.filter(Boolean);
      } else {
        state.data.from_history_template = false;
        state.data.history_questions = [];
      }
      const errors = validateBasics(state.data);
      if (errors.length) {
        return {
          reply: buildBasicsFormatTemplateReply(),
          step: 'await_basics',
          errors,
          ui: { type: 'basics_prompt' },
          done: false,
        };
      }
      return advanceToQuestionSource(state);
    }

    /* ─── Interview type (legacy — browser video only) ─── */
    if (state.step === 'choose_interview_type' || action === 'set_interview_type') {
      return advanceToQuestionSource(
        state,
        'Browser video interview selected.'
      );
    }

    /* ─── Phones (legacy telephony step — redirect to browser flow) ─── */
    if (state.step === 'enter_phones' || action === 'set_phones') {
      return advanceToQuestionSource(
        state,
        'Browser video interview is used for all sessions. Continuing with question setup.'
      );
    }

    /* ─── Question source ─── */
    if (state.step === 'choose_question_source' || action === 'set_question_source') {
      const v = String(value || message || '').toLowerCase();
      if (v === 'history' && state.data.from_history_template && state.data.history_questions?.length) {
        state.data.question_source = 'history';
        const historyPool = state.data.history_questions;
        state.data.questions = pickHistoryQuestions(state.data, historyPool);
        state.data.question_count = state.data.questions.length;
        state.step = 'choose_schedule';
        const trimmedNote =
          historyPool.length > state.data.questions.length
            ? ` (first ${state.data.questions.length} of ${historyPool.length} from history)`
            : '';
        return {
          reply: `Using ${state.data.questions.length} question(s) from history${trimmedNote}.`,
          step: state.step,
          questions: state.data.questions.map((q) => q.question),
          ui: {
            type: 'select',
            field: 'schedule_mode',
            label: 'When should the interview run?',
            options: [
              { value: 'now', label: 'Now (invite / call immediately)' },
              { value: 'later', label: 'Later (pick date & time)' },
            ],
          },
          done: false,
        };
      }
      if (v === 'ai' || v === 'generated') {
        state.data.question_source = 'ai';
        try {
          state.data.ai_question_pool = await generateQuestionPool(state.data, 25);
          const need = resolveQuestionCount(state.data) || 5;
          const picked = shufflePick(state.data.ai_question_pool, need);
          state.data.questions = picked.map((q, i) => ({ ...q, order: i + 1 }));
          state.data.question_count = state.data.questions.length;
          state.step = 'choose_schedule';
          return {
            reply: `Generated 25 questions and randomly selected ${need} for this interview.`,
            step: state.step,
            questions: state.data.questions.map((q) => q.question),
            ui: {
              type: 'select',
              field: 'schedule_mode',
              label: 'When should the interview run?',
              options: [
                { value: 'now', label: 'Now (invite / call immediately)' },
                { value: 'later', label: 'Later (pick date & time)' },
              ],
            },
            done: false,
          };
        } catch (e) {
          return { reply: `AI question generation failed: ${e.message}`, done: false, ui: { type: 'basics_prompt' } };
        }
      }
      if (v === 'manual' || v === 'your' || v === 'list') {
        state.data.question_source = 'manual';
        state.step = 'manual_questions';
        const need = resolveQuestionCount(state.data) || 3;
        return {
          reply: `Provide ${need} questions — type below, or upload a .txt file (one question per line).`,
          step: state.step,
          ui: {
            type: 'manual_questions',
            field: 'questions_text',
            required_count: need,
            label: `Your ${need} questions`,
            placeholder: '1. Tell me about yourself\n2. Explain Laravel MVC\n...',
            allow_file: true,
          },
          done: false,
        };
      }
      return {
        reply: 'Select question source from the dropdown.',
        step: 'choose_question_source',
        ui: {
          type: 'select',
          field: 'question_source',
          label: 'How do you want to provide interview questions?',
          options: questionSourceOptions(state.data),
        },
        done: false,
      };
    }

    /* ─── Manual questions ─── */
    if (state.step === 'manual_questions' || action === 'submit_manual_questions') {
      const need = resolveQuestionCount(state.data) || 3;
      const parsed = parseManualQuestions(questionsText || message, need);
      if (!parsed.ok) {
        return {
          reply: `Need exactly ${need} questions. You provided ${parsed.lines.length}. Add more lines.`,
          step: 'manual_questions',
          ui: {
            type: 'manual_questions',
            field: 'questions_text',
            required_count: need,
            label: `Your ${need} questions`,
            allow_file: true,
          },
          done: false,
        };
      }
      state.data.questions = parsed.questions;
      state.data.question_count = parsed.questions.length;
      state.step = 'choose_schedule';
      return {
        reply: `Saved ${need} questions.`,
        step: state.step,
        questions: state.data.questions.map((q) => q.question),
        ui: {
          type: 'select',
          field: 'schedule_mode',
          label: 'When should the interview run?',
          options: [
            { value: 'now', label: 'Now (invite / call immediately)' },
            { value: 'later', label: 'Later (pick date & time)' },
          ],
        },
        done: false,
      };
    }

    /* ─── Schedule now / later ─── */
    if (state.step === 'choose_schedule' || action === 'set_schedule_mode') {
      const v = String(value || message || '').toLowerCase();
      if (v === 'now') {
        state.data.schedule_mode = 'now';
        state.data.scheduled_at = moment().tz(state.data.timezone || DEFAULT_TZ).format('YYYY-MM-DD HH:mm:ss');
        state.step = 'confirm';
        return {
          reply: buildConfirmText(state.data),
          step: state.step,
          ui: { type: 'confirm', label: 'Confirm & schedule interview' },
          schedulePayload: buildSchedulePayload(state.data),
          done: false,
        };
      }
      if (v === 'later') {
        state.data.schedule_mode = 'later';
        state.step = 'ask_datetime';
        const candidates = state.data.candidates?.length
          ? state.data.candidates
          : buildCandidates(state.data);
        const prompt = laterDatetimePrompt(candidates);
        return {
          reply: prompt.reply,
          step: state.step,
          ui: prompt.ui,
          done: false,
        };
      }
      return {
        reply: 'Choose when to run the interview.',
        step: 'choose_schedule',
        ui: {
          type: 'select',
          field: 'schedule_mode',
          label: 'When should the interview run?',
          options: [
            { value: 'now', label: 'Now' },
            { value: 'later', label: 'Later' },
          ],
        },
        done: false,
      };
    }

    if (state.step === 'ask_datetime' || action === 'set_datetime') {
      const raw = message || value;
      const tz = state.data.timezone || DEFAULT_TZ;
      const candidates = state.data.candidates?.length
        ? state.data.candidates
        : buildCandidates(state.data);
      const timeEntries = parseTimeEntriesFromMessage(raw);

      if (timeEntries.length > 0 && candidates.length > 1) {
        const schedules = [];
        const errors = [];
        for (const entry of timeEntries) {
          const candidate = candidates.find((c) => c.phone === entry.phoneNumber);
          if (!candidate) {
            errors.push(`Phone number not in list: ${entry.phoneNumber}`);
            continue;
          }
          const parsed = parseDatetimeInput(entry.dateTimeStr, tz);
          if (!parsed.ok) {
            errors.push(`Invalid time for ${entry.phoneNumber}: ${entry.dateTimeStr}`);
            continue;
          }
          schedules.push({
            ...candidate,
            scheduled_at: parsed.scheduled_at,
            scheduled_at_utc: parsed.scheduled_at_utc,
          });
        }

        const scheduledPhones = new Set(schedules.map((s) => s.phone));
        const missing = candidates.filter((c) => !scheduledPhones.has(c.phone));
        if (missing.length && schedules.length) {
          const defaultSchedule = schedules[0];
          for (const c of missing) {
            schedules.push({
              ...c,
              scheduled_at: defaultSchedule.scheduled_at,
              scheduled_at_utc: defaultSchedule.scheduled_at_utc,
            });
          }
        }

        if (errors.length) {
          return {
            reply: `Please fix:\n${errors.map((e) => `• ${e}`).join('\n')}`,
            step: 'ask_datetime',
            ui: laterDatetimePrompt(candidates).ui,
            done: false,
          };
        }
        if (!schedules.length) {
          return {
            reply: 'Could not parse schedules. Use format: +919876543210 : 15-12-2026 11:00 AM',
            step: 'ask_datetime',
            ui: laterDatetimePrompt(candidates).ui,
            done: false,
          };
        }

        state.data.candidate_schedules = schedules;
        state.data.scheduled_at = schedules[0].scheduled_at;
        state.step = 'confirm';
        return {
          reply: buildConfirmText(state.data),
          step: state.step,
          ui: { type: 'confirm', label: 'Confirm & schedule interviews' },
          schedulePayload: buildSchedulePayload(state.data),
          done: false,
        };
      }

      const parsed = parseDatetimeInput(raw, tz);
      if (!parsed.ok) {
        return {
          reply: parsed.error || `Invalid date/time. Example: ${SCHEDULE_DATETIME_EXAMPLE}`,
          step: 'ask_datetime',
          ui: laterDatetimePrompt(candidates).ui,
          done: false,
        };
      }
      state.data.scheduled_at = parsed.scheduled_at;
      state.data.candidate_schedules = candidates.map((c) => ({
        ...c,
        scheduled_at: parsed.scheduled_at,
        scheduled_at_utc: parsed.scheduled_at_utc,
      }));
      state.step = 'confirm';
      return {
        reply: buildConfirmText(state.data),
        step: state.step,
        ui: {
          type: 'confirm',
          label: candidates.length > 1 ? 'Confirm & schedule interviews' : 'Confirm & schedule interview',
        },
        schedulePayload: buildSchedulePayload(state.data),
        done: false,
      };
    }

    return {
      reply: 'Paste job and candidate details to begin, or click Reset.',
      step: state.step,
      ui: { type: 'basics_prompt' },
      done: false,
    };
  },
};
